export default function Head() {
  return (
    <>
      <title>Next App</title>
      {/* <meta content="width=device-width, initial-scale=1" name="viewport" /> */}
      <meta name='viewport' content='minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover' />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
